batch_size: 128
class_weights:
- 0.1
- 0.9
dropout_rate: 0.5
image_size: 128
in_channels: 3
lambda_ce: 1
learning_rate: 0.001
weight_decay: 0.1
loss_function: poly1
model_name: effnetunet
num_epochs: 500
out_channels: 2
seed: 42
shuffle: true
transforms:
  general:
  - name: Transposed
    params:
      indices:
      - 2
      - 0
      - 1
      keys:
      - image
      - label
  - name: ToTensord
  - name: EnsureTyped
    params:
      dtype: float32
      keys:
      - image
      - label
  - name: Resized
    params:
      keys:
      - image
      - label
      spatial_size:
      - 128
      - 128
  train:
  # - name: RandGaussianNoised
  #   params:
  #     keys:
  #     - image
  #     mean: 0.0
  #     prob: 0.5
  #     std:
  #     - 8
  - name: RandFlipd
    params:
      keys:
      - image
      - label
      prob: 0.5
      spatial_axis:
      - 1
  - name: "RandAffined"
    params:
      keys: ["image", "label"]
      prob: 0.5
      spatial_size: [128, 128]
      rotate_range: [-0.05, 0.05]
      shear_range: [-0.01, 0.01]
      translate_range: [-10, 10]
      scale_range: [-0.1, 0.1]
      mode: "bilinear"
      padding_mode: "zeros"
      cache_grid: true
  # - name: RandZoomd
  #   params:
  #     keep_size: true
  #     keys:
  #     - image
  #     - label
  #     max_zoom: 1.1
  #     min_zoom: 0.9
  #     prob: 0.5
