# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Chris Yeung\Documents\PerkLab\aigt\SlicerExtension\LiveUltrasoundAi\LumpNavAISimulation\Resources\UI\LumpNavAISimulation.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LumpNavAISimulation(object):
    def setupUi(self, LumpNavAISimulation):
        LumpNavAISimulation.setObjectName("LumpNavAISimulation")
        LumpNavAISimulation.resize(364, 311)
        self.verticalLayout = QtWidgets.QVBoxLayout(LumpNavAISimulation)
        self.verticalLayout.setObjectName("verticalLayout")
        self.inputsCollapsibleButton = ctkCollapsibleButton(LumpNavAISimulation)
        self.inputsCollapsibleButton.setObjectName("inputsCollapsibleButton")
        self.formLayout_2 = QtWidgets.QFormLayout(self.inputsCollapsibleButton)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label = QtWidgets.QLabel(self.inputsCollapsibleButton)
        self.label.setObjectName("label")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label)
        self.modelPathLineEdit = ctkPathLineEdit(self.inputsCollapsibleButton)
        self.modelPathLineEdit.setObjectName("modelPathLineEdit")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.modelPathLineEdit)
        self.label_2 = QtWidgets.QLabel(self.inputsCollapsibleButton)
        self.label_2.setObjectName("label_2")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.caseDirectoryButton = ctkDirectoryButton(self.inputsCollapsibleButton)
        self.caseDirectoryButton.setObjectName("caseDirectoryButton")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.caseDirectoryButton)
        self.verticalLayout.addWidget(self.inputsCollapsibleButton)
        self.controlsCollapsibleButton = ctkCollapsibleButton(LumpNavAISimulation)
        self.controlsCollapsibleButton.setObjectName("controlsCollapsibleButton")
        self.formLayout_4 = QtWidgets.QFormLayout(self.controlsCollapsibleButton)
        self.formLayout_4.setObjectName("formLayout_4")
        self.verticalLayout.addWidget(self.controlsCollapsibleButton)
        self.resultsCollapsibleButton = ctkCollapsibleButton(LumpNavAISimulation)
        self.resultsCollapsibleButton.setCollapsed(True)
        self.resultsCollapsibleButton.setObjectName("resultsCollapsibleButton")
        self.verticalLayout.addWidget(self.resultsCollapsibleButton)
        self.advancedCollapsibleButton = ctkCollapsibleButton(LumpNavAISimulation)
        self.advancedCollapsibleButton.setCollapsed(True)
        self.advancedCollapsibleButton.setObjectName("advancedCollapsibleButton")
        self.formLayout_3 = QtWidgets.QFormLayout(self.advancedCollapsibleButton)
        self.formLayout_3.setObjectName("formLayout_3")
        self.verticalLayout.addWidget(self.advancedCollapsibleButton)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)

        self.retranslateUi(LumpNavAISimulation)
        QtCore.QMetaObject.connectSlotsByName(LumpNavAISimulation)

    def retranslateUi(self, LumpNavAISimulation):
        _translate = QtCore.QCoreApplication.translate
        self.inputsCollapsibleButton.setText(_translate("LumpNavAISimulation", "Inputs"))
        self.label.setText(_translate("LumpNavAISimulation", "Input model (model_traced.pt):"))
        self.label_2.setText(_translate("LumpNavAISimulation", "LumpNav recording folder:"))
        self.controlsCollapsibleButton.setText(_translate("LumpNavAISimulation", "Controls"))
        self.resultsCollapsibleButton.setText(_translate("LumpNavAISimulation", "Results"))
        self.advancedCollapsibleButton.setText(_translate("LumpNavAISimulation", "Advanced"))
from ctkCollapsibleButton import ctkCollapsibleButton
from ctkDirectoryButton import ctkDirectoryButton
from ctkPathLineEdit import ctkPathLineEdit
from qMRMLWidget import qMRMLWidget
